default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  host: localhost
  port: 3306
  username: root
  password: password

development:
  <<: *default
  database: contact_app_development

test:
  <<: *default
  database: contact_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10
  database: <%= ENV.fetch('DATABASE_NAME', 'contact_app_production') %>
